services:
    backend:
        build:
            context: ./feel-green-todo
            dockerfile: Dockerfile
        container_name: feel_green_todo_backend
        volumes:
            - ./feel-green-todo:/var/www/html
        depends_on:
            - db
        networks:
            - app_network

    db:
        image: mysql:8.0
        container_name: feel_green_todo_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: feel_green_todo
            MYSQL_USER: admin
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3308:3306"
        networks:
            - app_network

    nginx:
        image: nginx:latest
        container_name: feel_green_todo_nginx
        ports:
            - "8001:80" # http://localhost:8001
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./feel-green-todo/specification:/var/www/html/specification
        depends_on:
            - backend
        networks:
            - app_network

    swagger:
        image: swaggerapi/swagger-ui:latest
        container_name: feel_green_todo_swagger
        ports:
            - "8081:8080"
        environment:
            SWAGGER_JSON: /specification/index.yaml
        volumes:
            - ./feel-green-todo/specification:/specification

    mailhog:
        image: mailhog/mailhog
        container_name: feel_green_todo_mailhog
        restart: always
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - app_network

volumes:
    db_data:

networks:
    app_network:
